---
- name: create group for a user
  group: name={{item}} state=present
  with_items:
    - www-data
    - '{{box_user}}'

- name: create user
  user:
    name={{box_user}}
    shell=/bin/bash
    groups='{{box_user}},www-data'
    # if exists/ignore errors


- name: inject user ssh key
  authorized_key:
    user={{box_user}}
    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: inject_user_ssh_key


- name: inject additional ssh keys
  authorized_key: user={{box_user}} key='{{item}}'
  with_file: '{{inject_additional_ssh_keys}}'


- name: disallow password logins
  notify: restart ssh
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp="^\s*PasswordAuthentication" line="PasswordAuthentication no"


- name: enable paswordless sudo
  copy:
    dest=/etc/sudoers.d/{{box_user}}
    content="{{box_user}} ALL=(ALL) NOPASSWD:ALL"