---
- name: install software
  apt:
    state: present
    pkg: [
      'mc',
      'ntp',
      'git',
      'curl',
      'ncdu',
      'htop',
      'ncurses-dev'
    ]
  notify:
    - restart ntp
